Fixes Python Logging API Change
StackStorm/st2 pull request #4923
Opened 2020-04-27 02:07 UTC by Dahfizz9897

The logging module added a stacklevel=1 kwarg in python3.8 to the findCaller() function
We need to do the same since we override that method.

2020-04-27 02:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=4923) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=4923) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=4923) it.</sub>

2020-04-27 02:08 UTC, Dahfizz9897 commented
This fixes this issue: https://github.com/StackStorm/st2/issues/4922

2020-04-27 22:30 UTC, blag submitted a review, later dismissed
If the `stacklevel` parameter isn't actually used anywhere, it would probably be better to use `**kwargs` to capture it.

2020-04-28 23:55 UTC, Dahfizz9897 commented
Updated, but I had to use `*args, **kwargs` as the only parameters because other places in the logging library already call this function with the stacklevel parameter without specifying its name, so it would still error without an `*args`. And the existing `stack_info` wasn't used.

2020-09-29 19:11 UTC, nmaludy requested changes
Can you please add a CHANGELOG entry for this?

2020-10-01 19:17 UTC, nmaludy approved these changes

2020-10-02 13:51 UTC, armab commented on CHANGELOG.rst
> +  where the ``find_caller()`` function introduced some new variables. (bug fix)
```suggestion
  where the ``find_caller()`` function introduced some new variables. (bug fix) #4923
```

2020-10-05 11:54 UTC, merged