Fix for issue 4998 - Web Hook Rules check http headers in case sensitive manner
StackStorm/st2 pull request #5038
Opened 2020-09-10 04:28 UTC by Rand01ph

I have add a payload['headers_lower'] for webhook and add a unittest for this.

This fix for me the issue #4998

2021-03-07 06:41 UTC, cognifloyd commented
FYI: we just merged a change that reformats all the code with `black`. Please rebase on master (or merge master into your branch) and reformat your code with black as well. You can use `pre-commit install` to have `black` run on your commits. Thanks!

2021-09-06 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5038) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5038) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5038) it.</sub>

2021-10-05 21:45 UTC, cognifloyd requested changes
@Rand01ph could you please sign the CLA? (If you signed it before, you'll need to resign it now that it says "Linux Foundation" instead of one of the previous StackStorm stewards).

Also, I just resolved the conflicts, merged master into your branch, and reformatted with black.

I have one style suggestion.

I would like to merge your PR fairly quickly if you can help me at least with the CLA. Hopefully there's not much left before we can merge this.

2021-10-05 21:45 UTC, cognifloyd commented on st2api/st2api/controllers/v1/webhooks.py
> +            payload["headers_lower"] = dict((k.lower(), v) for k, v in headers.items())
```suggestion
            payload["headers_lower"] = {k.lower(): v for k, v in headers.items()}
```

2022-01-28 15:41 UTC, merged

2022-01-28 15:41 UTC, armab commented
Merged, thanks!