Exposing timeout parameter for packs.install action to help with long running installs.
StackStorm/st2 pull request #5047
Opened 2020-09-24 17:50 UTC by hnanchahal

Some packs can get a timeout after trying to set up virtual env for 600 sec. This can happen if someone is using persistent storage outside and there is latency in read/write. The default action timeout for packs.install action is controlled by the default timeout for the python_script action runner which is 600 sec. This change will allow to override the timeout.

2020-09-24 17:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5047) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5047) before we can accept your contribution.<br/><hr/>**hanancha** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5047) it.</sub>

2020-09-25 10:46 UTC, armab requested changes
That's really helpful @hnanchahal, thanks for the contribution! :+1: 

Everything looks good, we just need a changelog record for this enhancement. See CHANGELOG.rst for the examples and format to follow.

2020-09-25 18:46 UTC, armab commented on CHANGELOG.rst
> +  default timeout of 600 sec which is defined by the python_script action runner (improvement)
```suggestion
  default timeout of 600 sec which is defined by the python_script action runner (improvement) #5047
```

2020-09-25 19:22 UTC, hnanchahal commented on CHANGELOG.rst
> +  default timeout of 600 sec which is defined by the python_script action runner (improvement)
Added

2020-09-25 20:30 UTC, armab approved these changes
Looks good :+1: 

Thanks for the contribution!

2020-09-25 20:32 UTC, armab commented
@hnanchahal The only missing thing to merge the PR is CLA signing process, see https://github.com/StackStorm/st2/pull/5047#issuecomment-698493505 above for the instructions.

2020-09-29 19:15 UTC, nmaludy commented on contrib/packs/actions/workflows/install.yaml
>        python3: <% ctx().python3 %>
i'm wondering if this timeout should also be applied to other sub-actions such as the pack content registration (thinking EC2 pack where there is 1000+ actions)

2020-09-29 19:16 UTC, nmaludy reviewed
Question left inline about timeout parameter usage.

2020-10-01 18:44 UTC, nmaludy commented
@hnanchahal this PR is currently held up because you haven't signed our CLA (Contributor License Agreement), can you please do so and we'll be happy to merge this PR!

2020-10-01 19:15 UTC, nmaludy commented
Removing Milestone until CLA is signed

2020-11-19 00:58 UTC, hnanchahal commented
> Removing Milestone until CLA is signed

The old account hnanchah no longer has a backing email. That email is no longer valid so i am unable to add that as a secondary email and validate. Any other alternatives? Do you want me to submit a new PR?

2020-11-19 01:32 UTC, blag commented
If we just open a new PR, if you just cherry-pick the commits into a new branch and push, the commits will still be authored (in Git) by the now-invalid "hnanchah" account. I believe that we will need to generate brand new commits from scratch by manually copying and pasting the code between branches (eg: no simple `git cherry-pick` commits) and open a brand new PR with that branch.

@hnanchahal Can you not even login to the old "hnanchah" GitHub account? Is it tied into TFA or an old SSO or something?

2020-11-19 07:17 UTC, closed without merging

2020-11-19 07:17 UTC, hnanchahal commented
CLA Issues. Will raise a duplicate PR.