Allows GitLab SSH URL on pack actions
StackStorm/st2 pull request #5050
Opened 2020-10-01 14:39 UTC by asthLucas

Previously only GitHub based URL could be used for downloading and installing packs.

2020-10-01 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5050) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5050) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5050) it.</sub>

2020-10-01 19:57 UTC, nmaludy requested changes
@asthLucas Thanks a ton for the PR, this looks good!

Would you mind please adding an entry into `CHANGELOG.rst` ?

It also might help to add a PR to the https://github.com/StackStorm/st2docs repo so that others know that gitlab URLs can be used.

Thanks again!

2020-10-02 14:52 UTC, asthLucas commented
@nmaludy Thanks for the advice.

I`ve updated the changelog and the documentation.

2020-10-05 12:39 UTC, nmaludy approved these changes
@asthLucas Thanks for these changes, i'm approving them now but targeting them for the 3.4.0 release, 3.3.0 is change freeze tomorrow and i don't want to introduce any new changes before then.

2021-01-21 18:02 UTC, blag commented
I'm going to make this a blocker for v3.4 to ensure that it makes it in. I'll be working on fixing the end-to-end tests and rerunning them today.

2021-01-22 11:31 UTC, merged