fix for ticket #5078
StackStorm/st2 pull request #5091
Opened 2020-11-24 04:42 UTC by christopher-russell

2020-11-24 04:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5091) it.</sub>

2020-11-24 13:11 UTC, armab requested changes
Thanks for the PR! :+1: 

Can you please provide a Changelog for this fix so we'll be able to merge it?
Please also compose the PR Title/Description so it'll be more clear what this Pull Request does and why.

2020-11-25 12:15 UTC, armab requested changes

2020-11-25 12:15 UTC, armab commented on CHANGELOG.rst
> +* Added monkey patch fix to st2stream to enable it to work with mongodb via SSL.
Please follow the Changelog format including the PR number and type of the change if it's (bug fix) (enhancement), etc. See other examples below.
You're also welcome to include your Name or github Username as a contributor credit.

2020-11-26 03:41 UTC, punkrokk requested changes
Thanks for the PR, looks good just needs change log syntax updated.

2020-11-26 03:41 UTC, punkrokk commented on CHANGELOG.rst
> +* Added monkey patch fix to st2stream to enable it to work with mongodb via SSL. #5078 #5091
Can you add the (bug fix) part here to be consistent.

2020-11-26 11:38 UTC, armab approved these changes
Looks, good! 👍 
Merging.

2020-11-26 11:40 UTC, merged