use yaml.safe_load instead of yaml.load
StackStorm/st2 pull request #5159
Opened 2021-02-19 14:12 UTC by ashwini-orchestral

It is not safe to call yaml.load with any data received from an untrusted source. It allows instantiation of arbitrary objects.  The function yaml.safe_load limits this ability to simple Python objects like integers or lists. For security reasons, yaml.safe_load is used.

2021-02-19 18:33 UTC, m4dcoder requested changes
@ashwini-orchestral Looks like you included changes from another PR/commit into this PR. It is hard to tell what changes relate to this PR. Can you clean this up? You should branch from master and then apply the changes.

2021-02-22 22:13 UTC, Kami commented on st2common/st2common/util/spec_loader.py
> -        yaml.load(spec_string, UniqueKeyLoader)
This function is only used to load ``openapi.yaml.j2`` file which is controlled by us (developers), which means there should be no chance for "yaml type injection", but I do agree and still think it's better and safer to use ``yaml.safe_load``.

2021-02-22 22:14 UTC, Kami commented
@ashwini-orchestral As @m4dcoder said, please remove unrelated changes so we can review ``yaml.safe_load`` change in isolation.

2021-02-22 22:15 UTC, Kami commented
Superseded by #5162.

2021-02-22 22:15 UTC, closed without merging