Change minimum garbage_collection TTL to 1 day from 7
StackStorm/st2 pull request #5287
Opened 2021-06-14 19:56 UTC by ericreeves

A very simple change to modify the minimum TTL on the garbage collector, pulling it back to 1 day from 7.

2021-06-14 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5287) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5287) it.</sub>

2021-06-15 11:42 UTC, armab requested changes
Thanks for finding this setting and for the contribution @ericreeves ! :+1: 
We'll just need a CHANGELOG record for this and CLA signed based on Github bot message above.

Besides that, all good.

As for the current 3.5.0 we got code freeze already from the release team, the change will be included in the next release.

2021-06-16 11:12 UTC, armab commented on CHANGELOG.rst
> +* Reduced minimum TTL on garbage collection for action executions and trigger instances from 7 days to 1 day.
```suggestion
* Reduced minimum TTL on garbage collection for action executions and trigger instances from 7 days to 1 day. #5287
```

2021-06-16 11:13 UTC, armab approved these changes
:+1:

2021-07-04 09:41 UTC, Kami approved these changes
Yeah that change seems reasonable to me :+1:

2021-07-05 14:14 UTC, merged