Use Jinja sandboxed environment
StackStorm/st2 pull request #5359
Opened 2021-09-16 19:53 UTC by amanda11

2021-09-16 20:15 UTC, nzlosh approved these changes

2021-09-16 23:23 UTC, m4dcoder requested changes
- Do we need to update Jinja >= 2.11 in requirements?
- Please update orquesta version in requirements to use the commit with the similar fix (after https://github.com/StackStorm/orquesta/pull/240 is merged).
- Please add a changelog entry.
- Please update description of this PR on why this fix is needed.

2021-09-17 09:22 UTC, amanda11 commented
> * Do we need to update Jinja >= 2.11 in requirements?
> * Please update orquesta version in requirements to use the commit with the similar fix (after [StackStorm/orquesta#240](https://github.com/StackStorm/orquesta/pull/240) is merged).
> * Please add a changelog entry.
> * Please update description of this PR on why this fix is needed.

@m4dcoder I've addressed your requirements, Jinja is already at 2.11 in the requirements on ST2 requirements.

2021-09-18 01:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5359) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: amanda11<br/>:x: m4dcoder<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5359) it.</sub>

2021-09-18 01:18 UTC, m4dcoder approved these changes

2021-09-20 08:38 UTC, merged