Action delete API rework - support for action file deletion
StackStorm/st2 pull request #5360
Opened 2021-09-17 16:03 UTC by mahesh-orch

* Action delete API modification to have option to delete action database entry without removing files from disk
* From CLI `st2 action delete <pack>.<action>` will delete database entry only
* From CLI `st2 action delete --remove-files <pack>.<action>` will delete database entry and files.
* If action DELETE method has additional argument as `{"remove_files": true}` in the body then it will remove related action files from disk along with database entry.
* `{"remove_files": false}` or no additional argument in action DELETE method body will remove only database entry.
* Action delete API modification to have option to delete action database entry without removing files from disk
* From CLI `st2 action delete <pack>.<action>` will delete database entry only
* From CLI `st2 action delete --remove-files <pack>.<action>` will delete database entry and files.
* If action DELETE method has additional argument as `{"remove_files": true}` in the body then it will remove related action files from disk along with database entry.
* `{"remove_files": false}` or no additional argument in action DELETE method body will remove only database entry.

2021-09-17 23:57 UTC, m4dcoder requested changes

2021-09-17 23:57 UTC, m4dcoder commented on st2api/st2api/controllers/v1/actions.py
> +    def delete(self, files_remove_request, ref_or_id, requester_user):
Can you rename `files_remove_request` to `options`?

2021-09-17 23:57 UTC, m4dcoder commented on st2common/st2common/openapi.yaml.j2
> +        - name: files_remove_request
Can you rename `files_remove_request` to `options`?

2021-09-17 23:57 UTC, m4dcoder commented on st2common/st2common/openapi.yaml
> +        - name: files_remove_request
Can you rename `files_remove_request` to `options`?

2021-09-17 23:57 UTC, m4dcoder commented on st2client/st2client/commands/action.py
> +            help="Remove action files from disk.",
Do we need to add `default=False`?

2021-09-17 23:57 UTC, m4dcoder commented on st2client/st2client/commands/action.py
> +            remove_files = False
Since the remove_files arg is already defined as boolean above, you can change this if/else block to `remove_files = args.remove_files`.

2021-09-17 23:57 UTC, m4dcoder commented on st2api/tests/unit/controllers/v1/test_actions.py
> +
- Update existing unit test `test_delete` where there's no payload and assert database record is removed and mocked delete_action_files_from_pack is not called
- Add new unit test `test_delete_remove_files_false` where remove_files=False in payload and assert database record is removed and mocked delete_action_files_from_pack is not called
- Add new unit test `test_delete_remove_files_true` where remove_files=True in payload and assert database record is removed and mocked delete_action_files_from_pack is called

2021-09-20 18:05 UTC, ashwini-orchestral commented
@m4dcoder I have added unit tests, updated existing unit test and done other minor changes as suggested. Please review. Thanks.

2021-09-20 18:06 UTC, mahesh-orch commented
@m4dcoder I have added unit tests, updated existing unit test and done other minor changes as suggested. Please review. Thanks.

2021-09-20 20:14 UTC, m4dcoder approved these changes
LGTM

2021-09-20 22:51 UTC, nzlosh commented on st2client/st2client/commands/action.py
> +            "-rf",
Single hyphen flags should be a single letter only.  Under Linux, it's possible to have flags grouped by a single hyphen which would make the `-rf` flag seem like two flags `-r -f` were being passed. `-r` should be sufficient for the `remove_files` flag unless it's already taken.

2021-09-21 11:13 UTC, amanda11 reviewed
Just a minor comment on wording in the schema, but @nzlosh point more important.

2021-09-21 11:13 UTC, amanda11 commented on st2common/st2common/openapi.yaml.j2
> +        description: Force delete action files from disk
Minor comment - should this be reworded as in ohter schema, as its not really a force - its just a flag.

2021-09-21 14:09 UTC, mahesh-orch commented
@nzlosh I have changed CLI action delete optional argument `-rf` to `-r`.
@amanda11 I have updated the description of ActionDeleteSchema `remove-files` argument.
Please review. Thanks.

2021-09-21 15:13 UTC, nzlosh approved these changes

2021-09-21 18:28 UTC, merged