#5460 - Include pysocks in st2client
StackStorm/st2 pull request #5469
Opened 2021-12-01 08:47 UTC by kingsleyadam

Without pysocks PyPi package SOCKS proxies won't work with the following errors.

```
ERROR: Missing dependencies for SOCKS support.
```

2021-12-01 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=5469) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=5469) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=5469) it.</sub>

2022-01-05 20:58 UTC, armab requested changes
Thanks for the contribution!

Looks like the tests are passing.
Could you please include a Changelog for this PR as well?

2022-01-06 08:40 UTC, kingsleyadam commented
> Thanks for the contribution!
> 
> Looks like the tests are passing. Could you please include a Changelog for this PR as well?

Yep! Changelog updated.

2022-01-06 13:09 UTC, armab approved these changes

2022-01-06 13:10 UTC, merged

2022-01-06 13:10 UTC, armab commented
@kingsleyadam  Merged, thanks!