Add `pants-plugins/pack_metadata` to inform pants about our packs
StackStorm/st2 pull request #5868
Opened 2023-01-17 18:33 UTC by cognifloyd

### Background

This is another part of introducing [pants](https://www.pantsbuild.org/docs), as discussed in various TSC meetings.

Related PRs can be found in:
- [pantsbuild](https://github.com/StackStorm/st2/milestone/47) milestone (which includes PRs since #5713)
- https://github.com/StackStorm/st2/labels/pantsbuild label (which also includes preparatory PRs that came before adding pantsbuild)

### Overview of this PR

This PR makes it possible to inform pants about all of our pack metadata files by adding a new `pack_metadata` target. The `pack_metadata` target encompasses the following files:

https://github.com/StackStorm/st2/blob/185e871260000b579902c9de449204f905959f2f/pants-plugins/pack_metadata/target_types.py#L29-L40

Python, shell, and requirements files all need to be handled separately so that pants can lint/fmt them appropriately. Pants does not have a markdown plugin yet, so I put them in the list as a reminder that they will need to be dealt with, but I commented them out.

One of our packs is in a git submodule (`st2tests/st2tests/fixtures/packs/test_content_version`), so it also adds a `pack_metadata_in_git_submodule` target to cleanly handle a case where someone has not checked out the git submodules. This improves the Developer Experience by raising an error as early as possible to let people know that they need to checkout the git submodule and how to do that. Otherwise, they won't get an error until they run tests where we have some code to give the same instructions for the tests that need it.

Note that I have not enabled the plugin yet:
https://github.com/StackStorm/st2/blob/185e871260000b579902c9de449204f905959f2f/pants.toml#L28

That keeps this PR focused on the plugin itself including adding tests for it. The next PR will add the `pack_metadata` targets (at least in part using `./pants tailor ::`) in our BUILD files. If you want to explore some of that, you can look at: https://github.com/StackStorm/st2/compare/pants-plugins-pack_metadata...pants-pack_metadata

### Developing pants plugins

Pants has extensive documentation on the plugin API, including how to create targets, how to write rules, and there's even a mini tutorial about how to add a formatter (adding formatters is a very common thing for plugins to do).

- [Plugins overview](https://www.pantsbuild.org/docs/plugins-overview)
- [The Target API](https://www.pantsbuild.org/docs/target-api)
    - [Concepts](https://www.pantsbuild.org/docs/target-api-concepts) _eg: defines targets and fields._
    - [Creating new fields](https://www.pantsbuild.org/docs/target-api-new-fields)
    - [Creating new targets](https://www.pantsbuild.org/docs/target-api-new-targets)
- [The Rules API](https://www.pantsbuild.org/docs/rules-api)
- [Testing Plugins](https://www.pantsbuild.org/docs/rules-api-testing)

2023-01-18 12:40 UTC, rush-skills approved these changes

2023-01-20 15:40 UTC, amanda11 requested changes
Couple of typos

2023-01-20 15:40 UTC, amanda11 commented on pants-plugins/README.md
> +Pack metadata includes top-level files (`pack.yaml`, `<pack>.yaml.examle`,
```suggestion
Pack metadata includes top-level files (`pack.yaml`, `<pack>.yaml.example`,
```

2023-01-20 15:40 UTC, amanda11 commented on pants-plugins/pack_metadata/target_types.py
> +        "Pack metadata includes top-level files (pack.yaml, <pack>.yaml.examle, "
```suggestion
        "Pack metadata includes top-level files (pack.yaml, <pack>.yaml.example, "
```

2023-01-21 03:35 UTC, cognifloyd reviewed
Good catch! Fixed.

2023-01-23 15:18 UTC, amanda11 approved these changes
LGTM

2023-01-23 15:45 UTC, merged