Add Support for MongoDB 5, 6, 7 PYMONGO 4.6.1  Drop Python 3.6
StackStorm/st2 pull request #6079
Opened 2023-12-01 10:54 UTC by philipphomberger

1. Update PYMONGO to 4.6.1
2. Update mongoengine to 0.27.0
3. Remove Some Tets and Code because ssl_match_hostname parameter not exist in newer Version.

2023-12-01 16:14 UTC, armab requested changes
Good effort!
Please split changes into a two dedicated PRs.

One is about removing Python3.6 and another one about MongoDB (+pymongo) changes.
That'll help keeping things organized, good for history, testing and separates concerns.

2024-01-17 09:01 UTC, nzlosh commented
According to the migration documentation `ssl_match_hostname` functionality was not dropped but replaced by `tlsAllowInvalidHostnames` https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#renamed-uri-options

2024-01-17 12:41 UTC, philipphomberger commented
> According to the migration documentation `ssl_match_hostname` functionality was not dropped but replaced by `tlsAllowInvalidHostnames` https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#renamed-uri-options

okey. so id would be better to add this tlsAllowInvalidHostnames to replace the old ssl_match_hostname right ?

2024-01-17 13:46 UTC, nzlosh commented
I think the work for adding support for mongodb 5+ will require working through the official `migrate-to-pymongo4` document, checking the code base across the St2 repos (st2, orquesta, rbac, ldap, perhaps others) and update functions/methods/classes that reference the old v3 API.

The document recommends using pymongo 3.12 and turn on deprecation warnings to easily spot of the deprecated code.  There's also the fact that it should not be tested against python 3.6, but rather python3.8, which is to be our lowest supported version for the 3.9.0 release.

We have the choice of keeping `ssl_*` configuration names and transpose them to `tls` equivalent so that users don't need to adjust configuration files or update to use `tls` to reflect the correct name of the underlying technology being used.  Perhaps keeping ssl and tls versions for st2 v3.9.0 and with deprecation warnings of ssl version being removed in st2 v3.10

2024-01-23 07:56 UTC, philipphomberger commented
> I think the work for adding support for mongodb 5+ will require working through the official `migrate-to-pymongo4` document, checking the code base across the St2 repos (st2, orquesta, rbac, ldap, perhaps others) and update functions/methods/classes that reference the old v3 API.
> 
> The document recommends using pymongo 3.12 and turn on deprecation warnings to easily spot of the deprecated code. There's also the fact that it should not be tested against python 3.6, but rather python3.8, which is to be our lowest supported version for the 3.9.0 release.
> 
> We have the choice of keeping `ssl_*` configuration names and transpose them to `tls` equivalent so that users don't need to adjust configuration files or update to use `tls` to reflect the correct name of the underlying technology being used. Perhaps keeping ssl and tls versions for st2 v3.9.0 and with deprecation warnings of ssl version being removed in st2 v3.10

Thanks for the explanation. I thought it was too easy to just pull up the version.

2024-02-13 18:09 UTC, cognifloyd commented
I haven't read the PR, so this is a drive by comment after our TSC meeting.

Our codebase currently supports:
```
# mongoengine 0.24.0 has breaking changes to support pymongo 4.0
mongoengine>=0.21.0,<0.24.0
# pymongo 3.13 has backports of APIs from pymongo 4 to help w/ migration
pymongo>=3.11.0,<3.13.0
```

So, to update mongoengine/pymongo we need to migrate our code base based on:
https://docs.mongoengine.org/changelog.html#changes-in-0-24-0
https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html
https://pymongo.readthedocs.io/en/stable/changelog.html#changes-in-version-4-0

2024-05-10 00:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/StackStorm/st2?pullRequest=6079) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/StackStorm/st2?pullRequest=6079) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: philipphomberger<br/>:x: Philipp Homberger<br/><hr/>**Philipp Homberger** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/StackStorm/st2?pullRequest=6079) it.</sub>

2025-02-22 08:57 UTC, nzlosh commented
Thank you @philipphomberger for proposing this PR, it provided valuable insight into challenges to support MongoDB >4.4 as well as dropping Python3.6.  These features have been integrated into the master branch so this PR can be closed.

2025-02-22 08:57 UTC, closed without merging