Drop Python 3.6 Support for ST2 3.9.0
StackStorm/st2 pull request #6080
Opened 2023-12-04 06:55 UTC by philipphomberger

Update Pipeline Templates for Github and Circleci.

2024-01-20 10:52 UTC, nzlosh commented
@philipphomberger Is this MR ready for merge?

2024-01-23 07:54 UTC, philipphomberger commented
> @philipphomberger Is this MR ready for merge?

Yes I think so. 

Would be very helpful to update the PIP dependencies in small units.

2024-01-23 09:42 UTC, nzlosh approved these changes

2024-01-23 09:44 UTC, nzlosh commented
Good stuff!  Yes, we need to remove py3.6 testing to so we can start moving forward with adding mongodb and newer python versions.

2024-01-23 14:40 UTC, amanda11 reviewed
I am just wondering on best order to go about this...
We still have CI pipelines and build projects that are going to build python 3.6 images.
So it might be better to merge this PR after we have stopped the st2-packages and st2packaging-dockerfiles from requiring python 3.6 images.

2024-01-23 16:08 UTC, nzlosh commented
There's already work underway to remove py3.6 from st2 packaging which should arrive this week or the next.

2024-01-29 22:34 UTC, cognifloyd commented
I just merged #6118 which included dropping python3.6 from GHA. Sorry I didn't see your PR, or I would have merged this first.

2024-01-29 22:35 UTC, cognifloyd approved these changes

2024-04-19 19:07 UTC, cognifloyd requested changes
Would you move the changelog entry up to the in development section and adjust the wording to reflect the narrowed scope of this PR? Then I'll merge.

2024-04-22 11:11 UTC, philipphomberger commented
> Would you move the changelog entry up to the in development section and adjust the wording to reflect the narrowed scope of this PR? Then I'll merge.

done

2024-04-22 13:04 UTC, cognifloyd commented on CHANGELOG.rst
> +* Drop Python 3.6. Support. Update Pipeline Templates. #6080
```suggestion
* Drop Python 3.6 testing in CircleCI. #6080
```

2024-04-22 15:58 UTC, cognifloyd approved these changes

2024-04-22 16:08 UTC, merged