Refactor tools/launchdev.sh to use tmux
StackStorm/st2 pull request #6186
Opened 2024-04-19 06:38 UTC by cognifloyd

- Update launchdev.sh to use tmux instead of screen which is deprecated on rocky9
- revert st2api port change in tools/launchdev.sh
- use ellipses (...) more consistently
- pause in launchdev.sh for database init
- improve launchdev messaging
- remove screen references
- remove unused screen config files
- make gha log capture more useful
- gha: make sure we do not lose collected logs

2024-04-19 06:55 UTC, nzlosh approved these changes

2024-04-23 14:39 UTC, amanda11 requested changes

2024-04-23 14:39 UTC, amanda11 commented on tools/launchdev.sh
> +        eecho "Config file $ST2_CONF does not exist."
Why has this changed to eecho?

2024-04-23 14:42 UTC, amanda11 approved these changes

2024-04-23 16:29 UTC, merged