added no-store header to st2 nginx configuration
StackStorm/st2 pull request #6264
Opened 2024-10-19 07:44 UTC by fdrab

Added the no-store cache control header in order to prevent webui from serving cached and not up-to-date versions of opened workflows.

2024-10-23 15:37 UTC, fdrab commented
I have no idea how to set this for / location only. I've now tried everything. Is it an issue if this was a global header?

2024-10-24 13:44 UTC, guzzijones approved these changes
i have also seen this internally with our gui devs.  I am fine with no store cache on nginx.

2024-10-26 04:49 UTC, fdrab commented
Can you please validate with them where do they put the headers? I've put them into the / location, but it has been reported to me by my devs that this doesn't seem to work and they're still facing issues because they're loading stale flows from the cache. So, before this is merged, it would be nice if we knew whether this actually works.

2024-10-31 10:12 UTC, guzzijones requested changes
I was hoping this was the fix. I will have to dig a little deeper on my end.

2024-10-31 10:13 UTC, guzzijones commented
Have your users disabled their cache locally?

2024-10-31 15:53 UTC, fdrab commented
no, but I haven't asked them to (and all the guides on how to do this on the web are sort of... hacky). I've had a setup on a virtual machine, where the install was local and this was a set and forget kind of thing. But now I'm moving to EKS and while I can just set it in the st2web containers and reload nginx, I don't like the thought of doing this after every update to the pipeline that restarts the pods

2025-07-13 09:57 UTC, closed without merging